[package]
name = "hit-server"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]

[dependencies]
gotham = "0.2"
gotham_derive = "0.2"
hyper = "0.11"
futures = "0.1"
mime = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1.0"

anagram-hit-manager = { path = "../hit-manager" }
